-- Draft exercise catalog (general technique cues, not individualised coaching).
insert into exercises(name, muscle_group, equipment, difficulty, tracks, instructions) values
('Barbell Bench Press','Chest','Barbell','intermediate','weight_reps','Lie on a flat bench, lower the bar to mid-chest under control, press back up. Use a spotter or safety arms for heavy sets.'),
('Incline Dumbbell Press','Chest','Dumbbell','intermediate','weight_reps','Set bench to a low incline, press dumbbells up and slightly together, lower slowly.'),
('Push-up','Chest','Bodyweight','beginner','reps','Hands under shoulders, body in a straight line, lower chest to just above the floor, press up.'),
('Chest Fly (Cable)','Chest','Cable','intermediate','weight_reps','Slight elbow bend, bring handles together in an arc in front of the chest, return slowly.'),
('Overhead Press','Shoulders','Barbell','intermediate','weight_reps','Brace core, press the bar overhead in a straight line, lock out without leaning back.'),
('Dumbbell Shoulder Press','Shoulders','Dumbbell','beginner','weight_reps','Seated or standing, press dumbbells overhead, lower to ear level under control.'),
('Lateral Raise','Shoulders','Dumbbell','beginner','weight_reps','Raise dumbbells out to the sides to shoulder height with soft elbows, lower slowly.'),
('Face Pull','Shoulders','Cable','beginner','weight_reps','Pull the rope toward your face, elbows high, squeeze shoulder blades together.'),
('Pull-up','Back','Bodyweight','intermediate','reps','Hang from the bar, pull chest toward the bar, lower fully with control.'),
('Lat Pulldown','Back','Machine','beginner','weight_reps','Pull the bar to upper chest, leading with elbows, return slowly.'),
('Barbell Row','Back','Barbell','intermediate','weight_reps','Hinge at the hips with a flat back, pull the bar to the lower ribs, lower under control.'),
('Seated Cable Row','Back','Cable','beginner','weight_reps','Sit tall, pull handle to the torso, squeeze shoulder blades, return without rounding.'),
('Dumbbell Row','Back','Dumbbell','beginner','weight_reps','Support one hand on a bench, pull the dumbbell to the hip, lower fully.'),
('Deadlift','Back','Barbell','advanced','weight_reps','Bar over mid-foot, flat back, push the floor away and stand tall; start light and learn form first.'),
('Back Squat','Legs','Barbell','intermediate','weight_reps','Bar on upper back, sit down and back to at least parallel, keep knees tracking over toes, stand up.'),
('Goblet Squat','Legs','Dumbbell','beginner','weight_reps','Hold a dumbbell at the chest, squat between the knees keeping chest up.'),
('Leg Press','Legs','Machine','beginner','weight_reps','Feet shoulder-width on the platform, lower until knees are about 90 degrees, press without locking out hard.'),
('Romanian Deadlift','Legs','Barbell','intermediate','weight_reps','Soft knees, hinge back with a flat spine until a hamstring stretch, drive hips forward.'),
('Walking Lunge','Legs','Dumbbell','beginner','weight_reps','Step forward, lower the back knee toward the floor, push through the front heel to the next step.'),
('Leg Curl','Legs','Machine','beginner','weight_reps','Curl the pad toward the glutes, control the return.'),
('Leg Extension','Legs','Machine','beginner','weight_reps','Extend the knees until nearly straight, lower slowly.'),
('Hip Thrust','Glutes','Barbell','intermediate','weight_reps','Upper back on a bench, drive hips up until the torso is level, pause, lower.'),
('Standing Calf Raise','Calves','Machine','beginner','weight_reps','Rise onto the toes, pause at the top, lower to a full stretch.'),
('Biceps Curl','Arms','Dumbbell','beginner','weight_reps','Elbows by your sides, curl up without swinging, lower slowly.'),
('Hammer Curl','Arms','Dumbbell','beginner','weight_reps','Neutral grip, curl dumbbells toward the shoulders, lower slowly.'),
('Triceps Pushdown','Arms','Cable','beginner','weight_reps','Elbows pinned to your sides, extend fully, return under control.'),
('Overhead Triceps Extension','Arms','Dumbbell','beginner','weight_reps','Hold a dumbbell overhead with both hands, lower behind the head, extend.'),
('Dips','Arms','Bodyweight','intermediate','reps','Lower until upper arms are about parallel to the floor, press up; skip if it hurts the shoulders.'),
('Plank','Core','Bodyweight','beginner','duration','Forearms on the floor, body in a straight line, brace the core and breathe.'),
('Hanging Knee Raise','Core','Bodyweight','intermediate','reps','Hang from a bar, raise the knees toward the chest without swinging, lower slowly.'),
('Cable Crunch','Core','Cable','beginner','weight_reps','Kneel facing the cable, curl the ribs toward the hips, return slowly.'),
('Kettlebell Swing','Full body','Kettlebell','intermediate','weight_reps','Hinge and drive the hips to swing the bell to chest height, keep a flat back.'),
('Bodyweight Squat','Legs','Bodyweight','beginner','reps','Feet shoulder-width, sit back and down, stand up through the heels.'),
('Glute Bridge','Glutes','Bodyweight','beginner','reps','Lie on your back, knees bent, lift the hips until the body forms a line, lower slowly.'),
('Burpee','Full body','Bodyweight','intermediate','reps','Squat, jump back to a plank, return and jump up; scale down if needed.'),
('Mountain Climber','Core','Bodyweight','beginner','duration','From a plank, alternate driving the knees toward the chest at a steady pace.');
